# Generated by Django 3.2.6 on 2021-09-10 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_autorizan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Autorizan',
        ),
    ]
