# Generated by Django 3.2.6 on 2021-09-10 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='autorizan',
            name='documento',
            field=models.CharField(choices=[('C', 'CARNET')], default='C', max_length=20),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='documento',
            field=models.CharField(choices=[('C', 'CARNET')], default='D', max_length=20),
        ),
    ]
