# Generated by Django 3.2.6 on 2021-09-10 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_estudiante_art'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='art',
        ),
        migrations.AddField(
            model_name='articulo',
            name='est',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.articulo'),
        ),
    ]
