# Generated by Django 3.2.6 on 2021-09-10 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20210910_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='est',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.estudiante'),
        ),
    ]
