# Generated by Django 3.2.6 on 2021-09-10 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_articulo_est'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Autorizan',
            new_name='Administradores',
        ),
    ]
