# Generated by Django 3.2.6 on 2021-09-10 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_rename_autorizan_administradores'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='ad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.administradores'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='art',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.articulo'),
        ),
    ]
