# Generated by Django 3.2.6 on 2021-09-10 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20210910_1718'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articulo',
            old_name='est',
            new_name='autor',
        ),
        migrations.RenameField(
            model_name='articulo',
            old_name='ad',
            new_name='autorizante',
        ),
    ]
