# Generated by Django 3.2.6 on 2021-09-10 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20210910_1721'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='art',
            new_name='articulo',
        ),
    ]
